test_cases = {
    "phazed_group_type":
    [
        ("""submission.phazed_group_type(['2H', '2S', '2C'])""", [1]), 
        ("""submission.phazed_group_type(['AH', '2S', '2C'])""", [1]), 
        ("""submission.phazed_group_type(['AH', '2S', 'AC'])""", []), 
        ("""submission.phazed_group_type(['2S', '3S', '4S', '5S', '6S', '7S', '8S'])""", [2]), 
        ("""submission.phazed_group_type(['2S', '3S', '4S', '5S', '6S', 'AC', '7S'])""", [2]), 
        ("""submission.phazed_group_type(['2S', '3S', '4S', '5S', '6S', 'AC', '7S', '7S'])""", []), 
        ("""submission.phazed_group_type(['2S', '2S', '2C', '2H'])""", [3]), 
        ("""submission.phazed_group_type(['AC', '2S', '2S', '2C'])""", [3]), 
        ("""submission.phazed_group_type(['2S', '2S', '2C', '3H'])""", []), 
        ("""submission.phazed_group_type(['AC', 'AS', 'AS', '2C'])""", []), 
        ("""submission.phazed_group_type(['AC', 'AS', 'AC', 'AH'])""", []), 
        ("""submission.phazed_group_type(['2S', '3S', '4S', '5S', '6S', '7S', '8S', '9H'])""", [4]), 
        ("""submission.phazed_group_type(['2S', '3S', '4S', '5S', '6S', '7S', 'AS', '9H'])""", [4]), 
        ("""submission.phazed_group_type(['AC', '2S', '3S', '4S', '5S', '6S', '7S', 'AS'])""", [4]), 
        ("""submission.phazed_group_type(['2S', '3S', '4S', '5S', '6S', '7S', '9H', 'AS'])""", []), 
        ("""submission.phazed_group_type(['2S', '3S', '4S', '5S', '6S', '7S', '8S', '0H'])""", []), 
        ("""submission.phazed_group_type(['2S', '3S', '4S', '5S'])""", [5]), 
        ("""submission.phazed_group_type(['2C', '3S', '4C', '5S'])""", [5]), 
        ("""submission.phazed_group_type(['2C', 'AH', '4C', 'AD'])""", [5]), 
        ("""submission.phazed_group_type(['2C', 'AH', '4C', 'AD', '6S'])""", []), 
        ("""submission.phazed_group_type(['AH', '2C', '4C', 'AD'])""", []), 
        ("""submission.phazed_group_type(['AH', '2C', 'AC', 'AD'])""", []), 
        ("""submission.phazed_group_type(['2C', '3S', '4C', '5H'])""", []), 
        ("""submission.phazed_group_type(['2C', '3S', '4C', 'KS'])""", []), 
        ("""submission.phazed_group_type(['AH', '3S', '4C', 'KS'])""", []), 
        ("""submission.phazed_group_type(['AH', '2C', '3S', 'KS'])""", []), 
        ("""submission.phazed_group_type(['AH', '3S', 'AC', 'KS'])""", []), 
        ("""submission.phazed_group_type(['AH', '3S', 'AC', 'KS', 'KH', '3C'])""", [6]), 
        ("""submission.phazed_group_type(['AS', '3S', 'AC', 'KS', 'KC', '3C'])""", [6, 7]), 
        ("""submission.phazed_group_type(['KH', 'KC', '8H'])""", [6]), 
    ],

    "phazed_phase_type":
    [
        ("""submission.phazed_phase_type([['7D', '7S', '7H'], ['8D', '8S', '8D']])""", [1]), 
        ("""submission.phazed_phase_type([['7D', '7S', 'AH'], ['8D', 'AS', '8D']])""", [1]), 
        ("""submission.phazed_phase_type([['7D', '7S', 'AH'], ['8D', 'AS', 'AD']])""", []), 
        ("""submission.phazed_phase_type([['7D', '7S', 'AH'], ['8D', 'AS', '8D', '8H']])""", []), 
        ("""submission.phazed_phase_type([['9D', '6D', '2D', '3D', '0D', '0D', 'JD']])""", [2]), 
        ("""submission.phazed_phase_type([['9D', '6D', 'AS', '3D', '0D', '0D', 'JD']])""", [2]), 
        ("""submission.phazed_phase_type([['9D', '6D', '2D', '3D', '0D', '0D']])""", []), 
        ("""submission.phazed_phase_type([['9D', '6D', '2D', '3D', '0D', '0D', 'JD', 'QD']])""", []), 
        ("""submission.phazed_phase_type([['7D', '7S', '7H', '7D'], ['8D', '8S', '8D', '8H']])""", [4]), 
        ("""submission.phazed_phase_type([['AD', '7S', 'AH', '7D'], ['AD', '8S', '8D', 'AH']])""", [4]), 
        ("""submission.phazed_phase_type([['7D', '7S', '7H', '7D', '7S'], ['8D', '8S', '8D', '8H']])""", []), 
        ("""submission.phazed_phase_type([['AD', '7S', 'AH', '7D'], ['AD', '8S', 'AD', 'AH']])""", []), 
        ("""submission.phazed_phase_type([['2D', '3C', '4D', '5H', '6C', '7D', '8H', '9S']])""", [5]), 
        ("""submission.phazed_phase_type([['2D', 'AC', '4D', 'AH', '6C', '7D', '8H', 'AS']])""", [5]), 
        ("""submission.phazed_phase_type([['AH', '2D', '3C', '4D', '5H', '6C', '7D', '8H']])""", [5]), 
        ("""submission.phazed_phase_type([['2D', '3C', '4D', '5H', '6C', '7D', '8H', '9S', '0D']])""", []), 
        ("""submission.phazed_phase_type([['2D', '3H', '4D', '5H'], ['6C', '6D', '6H', '6S']])""", [7]), 
        ("""submission.phazed_phase_type([['2D', '3H', '4D', 'AH'], ['6C', 'AD', '6H', '6S']])""", [7]), 
        ("""submission.phazed_phase_type([['2D', '3C', '4D', 'AH'], ['6C', 'AD', '6H', '6S']])""", []), 
        ("""submission.phazed_phase_type([['2D', '3H', '4D', 'AH', '6H'], ['6C', 'AD', '6H', '6S']])""", []), 
    ],

    "phazed_is_valid_play":
    [
        ("""submission.phazed_is_valid_play((1, 'XX'), 0, [(None, []), (None, []), (None, []), (None, [])], [(0, [(1, 'XX')])], [3, 0, 0, 0], ['QC', 'KS', 'AH', 'AH', 'AD', 'AC', 'AC', 'AS', 'AH', 'KH', 'KS'], '7H')""", False),
        ("""submission.phazed_is_valid_play((2, '7H'), 0, [(None, []), (None, []), (None, []), (None, [])], [(0, [(1, 'XX')])], [3, 0, 0, 0], ['QC', 'KS', 'AH', 'AH', 'AD', 'AC', 'AC', 'AS', 'AH', 'KH', 'KS'], '7H')""", False),
        ("""submission.phazed_is_valid_play((3, (2, [['2C', 'AC', '4C', '5C', '6C', '7C', '8C']])), 0, [(None, []), (None, []), (None, []), (None, [])], [(0, [(1, 'XX')])], [1, 0, 0, 0], ['2C', '4C', '5C', '6C', '7C', '8C', '8C', '9C', 'AC', 'AS', 'KS'], '7S')""", True),
        ("""submission.phazed_is_valid_play((5, '7C'), 0, [(None, []), (None, []), (None, []), (None, [])], [(0, [(1, 'XX')])], [1, 0, 0, 0], ['2C', '4C', '5C', '6C', '7C', '8C', '8C', '9C', 'AC', 'AS', 'KS'], '7S')""", True),
        ("""submission.phazed_is_valid_play((5, '2S'), 0, [(None, []), (1, [['6C', '6S', '6D'], ['JC', 'JD', 'JH']]), (None, []), (None, [])], [(1, [(1, 'XX'), (5, 'QD')]), (2, [(1, 'XX'), (5, '0C')]), (3, [(1, 'XX'), (5, '4S')]), (0, [(1, 'XX'), (5, '3C')]), (1, [(1, 'XX'), (5, '0H')]), (2, [(1, 'XX'), (5, '9C')]), (3, [(2, '9C'), (5, '6S')]), (0, [(1, 'XX'), (5, 'JH')]), (1,  [(2, 'JH'),   (3, [['6C', '6S', '6D'], ['JC', 'JD', 'JH']]),   (5, '4C')]), (2, [(1, 'XX'), (5, '9C')]), (3, [(2, '9C'), (5, '7H')]), (0, [(1, 'XX')])], [0, 1, 0, 0], ['2C', '2H', '5D', '6C', '8S', '0C', 'KD', 'AD', 'AD', '2S','KS'], 'QS')""", True),
        ("""submission.phazed_is_valid_play((3, (1, [['2C', '2H', '2S'], ['KS', 'KD', 'AD']])), 0, [(None, []), (1, [['6C', '6S', '6D'], ['JC', 'JD', 'JH']]), (None, []), (None, [])], [(1, [(1, 'XX'), (5, 'QD')]), (2, [(1, 'XX'), (5, '0C')]), (3, [(1, 'XX'), (5, '4S')]), (0, [(1, 'XX'), (5, '3C')]), (1, [(1, 'XX'), (5, '0H')]), (2, [(1, 'XX'), (5, '9C')]), (3, [(2, '9C'), (5, '6S')]), (0, [(1, 'XX'), (5, 'JH')]), (1,  [(2, 'JH'),   (3, [['6C', '6S', '6D'], ['JC', 'JD', 'JH']]),   (5, '4C')]), (2, [(1, 'XX'), (5, '9C')]), (3, [(2, '9C'), (5, '7H')]), (0, [(1, 'XX')])], [0, 1, 0, 0], ['2C', '2H', '5D', '6C', '8S', '0C', 'KD', 'AD', 'AD', '2S', 'KS'], 'QS')""", True),
        ("""submission.phazed_is_valid_play((3, (4, [['2C', '2H', '2S', 'AD'], ['KS', 'KD', 'AD', 'AH']])), 0, [(None, []), (1, [['6C', '6S', '6D'], ['JC', 'JD', 'JH']]), (None, []), (None, [])], [(1, [(1, 'XX'), (5, 'QD')]), (2, [(1, 'XX'), (5, '0C')]), (3, [(1, 'XX'), (5, '4S')]), (0, [(1, 'XX'), (5, '3C')]), (1, [(1, 'XX'), (5, '0H')]), (2, [(1, 'XX'), (5, '9C')]), (3, [(2, '9C'), (5, '6S')]), (0, [(1, 'XX'), (5, 'JH')]), (1,  [(2, 'JH'),   (3, [['6C', '6S', '6D'], ['JC', 'JD', 'JH']]),   (5, '4C')]), (2, [(1, 'XX'), (5, '9C')]), (3, [(2, '9C'), (5, '7H')]), (0, [(1, 'XX')])], [0, 1, 0, 0], ['2C', '2H', '5D', '6C', '8S', 'AH', 'KD', 'AD', 'AD', '2S', 'KS'], 'QS')""", False),
        ("""submission.phazed_is_valid_play((4, ('6C', (1, 0, 0))), 0, [(None, []), (1, [['6C', '6S', '6D'], ['JC', 'JD', 'JH']]), (None, []), (None, [])], [(1, [(1, 'XX'), (5, 'QD')]), (2, [(1, 'XX'), (5, '0C')]), (3, [(1, 'XX'), (5, '4S')]), (0, [(1, 'XX'), (5, '3C')]), (1, [(1, 'XX'), (5, '0H')]), (2, [(1, 'XX'), (5, '9C')]), (3, [(2, '9C'), (5, '6S')]), (0, [(1, 'XX'), (5, 'JH')]), (1,  [(2, 'JH'),   (3, [['6C', '6S', '6D'], ['JC', 'JD', 'JH']]),   (5, '4C')]), (2, [(1, 'XX'), (5, '9C')]), (3, [(2, '9C'), (5, '7H')]), (0, [(1, 'XX')])], [0, 1, 0, 0], ['2C', '2H', '5D', '6C', '8S', 'AH', 'KD', 'AD', 'AD', '2S', 'KS'], 'QS')""", False),
	],

    # "phazed_score":
    # [
    #     ("""submission.phazed_score(['2C', '2H', '5D', '6C', '8S', 'AH', 'KD', 'AD', 'AD', '2S', 'KS'])""", 126), 
    #     ("""submission.phazed_score(['7D', 'AH'])""", 32), 
    #     ("""submission.phazed_score(['4C', '7S', '9C', 'AH', 'AD', 'KD', '0D', '9D', '9S', '4D', '9C'])""", 124), 
    #     ("""submission.phazed_score(['2C', '4C', '5C', '6C', '7C', '8C', '8C', '9C', 'AC', 'AS', 'KS'])""", 112), 
    #     ("""submission.phazed_score(['2C', '4C'])""", 6), 
    #     ("""submission.phazed_score(['AC'])""", 25), 
    # ],

}
